/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import com.skype.Call;
import com.skype.Skype;
import com.skype.SkypeException;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SMuherejee
 */
public class main extends javax.swing.JFrame {

    adjMicro adjM = new adjMicro();
    adjustMic adjM2 = new adjustMic();
    String wrok_dir = "C:\\SPIC-Client\\";
    public utility U = new utility();

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        test_mic = new javax.swing.JButton();
        start_exp = new javax.swing.JButton();
        threshold = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Self_test3 = new javax.swing.JButton();
        test_mic2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        test_mic.setText("Test Mic");
        test_mic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test_micActionPerformed(evt);
            }
        });

        start_exp.setText("Start Experiment");
        start_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_expActionPerformed(evt);
            }
        });

        threshold.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        threshold.setText("0.12");

        jLabel1.setText("Current Mic Sensetivity");

        Self_test3.setText("Self Test");
        Self_test3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Self_test3ActionPerformed(evt);
            }
        });

        test_mic2.setText("Test Mic 2");
        test_mic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test_mic2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(start_exp))
                    .addComponent(Self_test3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(threshold)
                            .addComponent(jLabel1))
                        .addGap(19, 19, 19)
                        .addComponent(test_mic)
                        .addGap(18, 18, 18)
                        .addComponent(test_mic2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(test_mic)
                    .addComponent(threshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(test_mic2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Self_test3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(start_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_expActionPerformed
        // TODO add your handling code here:
        client client = new client();
        client.setSensetivity(threshold.getText());
        client.setup();
        client.setVisible(true);
        client.setLocationRelativeTo(null);
    }//GEN-LAST:event_start_expActionPerformed

    private void test_micActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test_micActionPerformed
        // TODO add your handling code here:
        adjM.setVisible(true);
    }//GEN-LAST:event_test_micActionPerformed

    private void Self_test3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Self_test3ActionPerformed
        // TODO add your handling code here:
        self_server self = new self_server();
        self.setSensetivity(threshold.getText());
        self.loadData();
        self.setVisible(true);
    }//GEN-LAST:event_Self_test3ActionPerformed

    private void test_mic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test_mic2ActionPerformed
        // TODO add your handling code here:
        adjM2.setVisible(true);
        adjM2.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                threshold.setText(adjM2.getSFValue());
            }
        });
    }//GEN-LAST:event_test_mic2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main m = new main();
                m.setVisible(true);
                m.setLocationRelativeTo(null);
            }
        });
    }

    public void setSensetivity(String value) {
        threshold.setText(value);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Self_test3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton start_exp;
    private javax.swing.JButton test_mic;
    private javax.swing.JButton test_mic2;
    private javax.swing.JTextField threshold;
    // End of variables declaration//GEN-END:variables
}
